spring.application.name=Restaurantbackend
server.port=${PORT:8182}

# ==========================================
# PostgreSQL (Dynamic for Render & Local)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Arun@2003}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.data-locations=classpath:data.sql

admin.email=arunrajput16177@gmail.com

secretValue=weugfwreiuhtyiurthur5thuiheruhyhrtiudghiurtyhuirthuyhiurthy
#security........................
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.open-in-view=false

#spring.jpa.show-sql=true
#logging.level.org.springframework.security=DEBUG

#
#logging.level.org.springframework.transaction=TRACE
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#
#


spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true


#Outhauthication.............................
logging.level.org.springframework.security.oauth2.client.web=TRACE
logging.level.org.springframework.security.web.savedrequest=TRACE
logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.org.springframework.security.web.access.ExceptionTranslationFilter=DEBUG
logging.level.org.springframework.security=DEBUG


#Emailpassword
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy452t@gmail.com
spring.mail.password=vvzlxileldmqhtxh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.properties.mail.smtp.pool=true
spring.mail.properties.mail.smtp.pool.size=5

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#redis
spring.cache.type=redis
spring.data.redis.host=redis-15771.c10.us-east-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=15771
spring.data.redis.password=6gcF9ulxAwwMNDGDlenGoxi9xSDSBSw9



CLOUDINARY_CLOUD_NAME=ulwtxut7
CLOUDINARY_API_KEY=621966762129916
CLOUDINARY_API_SECRET=2q2b5IZuCnQ509y9NUHi3-m-lEo


# 1. Tomcat Parameter & File Limits (Set high numbers)
server.tomcat.max-parameter-count=1000
server.tomcat.max-file-count=100



#razorypay

RAZOR_PAY_KEY=rzp_test_TPzJJBQAsXQvXz
RAZOR_PAY_SECRET=sfOZCo02guRFegaga5OzoOZ5




//hikaripoolConfiguration

# Maximum number of connections in the pool (match to your database capacity)
spring.datasource.hikari.maximum-pool-size=20

# Minimum idle connections to keep alive
spring.datasource.hikari.minimum-idle=5

# How long a thread will wait for a connection before throwing an exception (in milliseconds)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000



//apikey

api_Url=https://api.weatherapi.com/v1
api_key=cc2137d72d6c415fb5362025263008





# ==========================================
# Apache Kafka (Dynamic for Aiven & Local)
# ==========================================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=email-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.arun.Restaurantbackend.DTO

spring.kafka.properties.security.protocol=${SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.properties.sasl.mechanism=${SPRING_KAFKA_PROPERTIES_SASL_MECHANISM:}
spring.kafka.properties.sasl.jaas.config=${SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG:}


springdoc.swagger-ui-path=/docs