
server.port=${PORT:10000}
#spring.profiles.active=prod
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.data-locations=classpath:data.sql


spring.kafka.consumer.max-poll-records=50
spring.kafka.consumer.properties.fetch.max.bytes=5242880
spring.kafka.consumer.properties.max.partition.fetch.bytes=1048576